export const QueryTypes = {
    FETCH_SQL_QUERY_PROCESSING: 'FETCH_SQL_QUERY_PROCESSING',
    FETCH_SQL_QUERY_SUCCESS: 'FETCH_SQL_QUERY_SUCCESS',
    FETCH_SQL_QUERY_ERROR: 'FETCH_SQL_QUERY_ERROR',
    RECEIVED_SQL_QUERY_DATA: 'RECEIVED_SQL_QUERY_DATA',
    
    FETCH_ALL_TABLES_PROCESSING: 'FETCH_ALL_TABLES_PROCESSING',
    FETCH_ALL_TABLES_SUCCESS: 'FETCH_ALL_TABLES_SUCCESS',
    FETCH_ALL_TABLES_ERROR: 'FETCH_ALL_TABLES_ERROR',
    RECEIVED_ALL_TABLES_DATA: 'RECEIVED_ALL_TABLES_DATA',
    
    SAVE_QUERY: 'SAVE_QUERY',
    REMOVE_QUERY: 'REMOVE_QUERY',
    ADD_QUERY_HISTORY: 'ADD_QUERY_HISTORY',
    ADD_QUERY_TIME: 'ADD_QUERY_TIME',
}